### ISSUE TITLE
Verify Bot's Handling of Long and Complex Queries

### ISSUE THREAD

**Issue by abheek-das** [John-Doe-TypeB/QOS-Testing#10]
Test how the chatbot processes long, multi-part, or overly complex queries. Ensure that it can break down and respond to such queries appropriately or ask for clarification if needed.

**Comment by John-Doe-TypeB** [comment]
Tested with long, multi-part queries, and the bot struggled to process the full request. It only addressed the first part of the query and ignored the rest. The bot should be able to break down and respond to each part of the input.

**Comment by abheek-das** [comment]
Tried some complex queries with multiple conditions and nested statements. The bot gave vague responses and didn't clarify what part of the query was causing the confusion. A follow-up question would improve its handling of complex requests.

**Comment by John-Doe-TypeB** [comment]
After tuning, the bot now processes long and multi-part queries better. It can handle multiple conditions and asks for clarification when it encounters nested statements. Marking this issue as resolved.
